/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import type {
  MockAccessControlV2BadRevision,
  MockAccessControlV2BadRevisionInterface,
} from "../MockAccessControlV2BadRevision";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_lensHub",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    inputs: [],
    name: "CannotInitImplementation",
    type: "error",
  },
  {
    inputs: [],
    name: "Initialized",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "requestorAddress",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "profileId",
        type: "uint256",
      },
      {
        internalType: "bytes",
        name: "data",
        type: "bytes",
      },
    ],
    name: "hasAccess",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "initialize",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "randomNumber",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

const _bytecode =
  "0x60c060405260008055600760015534801561001957600080fd5b506040516103a53803806103a58339810160408190526100389161004d565b306080526001600160a01b031660a05261007d565b60006020828403121561005f57600080fd5b81516001600160a01b038116811461007657600080fd5b9392505050565b60805160a0516103046100a16000396000609d0152600061014001526103046000f3fe608060405234801561001057600080fd5b50600436106100415760003560e01c806309cebe76146100465780638129fc1c1461006e578063ccbac9f514610078575b600080fd5b6100596100543660046101dd565b61008f565b60405190151581526020015b60405180910390f35b61007661013c565b005b61008160015481565b604051908152602001610065565b6000836001600160a01b03167f00000000000000000000000000000000000000000000000000000000000000006001600160a01b0316636352211e856040518263ffffffff1660e01b81526004016100e991815260200190565b602060405180830381865afa158015610106573d6000803e3d6000fd5b505050506040513d601f19601f8201168201806040525081019061012a91906102aa565b6001600160a01b031614949350505050565b60017f00000000000000000000000000000000000000000000000000000000000000006001600160a01b0316301415610188576040516325c7410560e21b815260040160405180910390fd5b60005481116101aa576040516302ed543d60e51b815260040160405180910390fd5b600055565b6001600160a01b03811681146101c457600080fd5b50565b634e487b7160e01b600052604160045260246000fd5b6000806000606084860312156101f257600080fd5b83356101fd816101af565b925060208401359150604084013567ffffffffffffffff8082111561022157600080fd5b818601915086601f83011261023557600080fd5b813581811115610247576102476101c7565b604051601f8201601f19908116603f0116810190838211818310171561026f5761026f6101c7565b8160405282815289602084870101111561028857600080fd5b8260208601602083013760006020848301015280955050505050509250925092565b6000602082840312156102bc57600080fd5b81516102c7816101af565b939250505056fea2646970667358221220cdec7a6c7aa618eb7d16323599cb662f935c2be2b7cece6082cc4c60703f36cf64736f6c634300080a0033";

type MockAccessControlV2BadRevisionConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: MockAccessControlV2BadRevisionConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class MockAccessControlV2BadRevision__factory extends ContractFactory {
  constructor(...args: MockAccessControlV2BadRevisionConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  deploy(
    _lensHub: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<MockAccessControlV2BadRevision> {
    return super.deploy(
      _lensHub,
      overrides || {}
    ) as Promise<MockAccessControlV2BadRevision>;
  }
  getDeployTransaction(
    _lensHub: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(_lensHub, overrides || {});
  }
  attach(address: string): MockAccessControlV2BadRevision {
    return super.attach(address) as MockAccessControlV2BadRevision;
  }
  connect(signer: Signer): MockAccessControlV2BadRevision__factory {
    return super.connect(signer) as MockAccessControlV2BadRevision__factory;
  }
  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): MockAccessControlV2BadRevisionInterface {
    return new utils.Interface(_abi) as MockAccessControlV2BadRevisionInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): MockAccessControlV2BadRevision {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as MockAccessControlV2BadRevision;
  }
}
